dist: bionic

env:
  - DB=postgres

services:
  - postgresql

language: ruby

cache: bundler

before_install:
  - gem update --system
  - gem --version
  - gem install bundler
  - sudo service postgresql restart

before_script:
  - cp config/database.postgres.yml config/database.yml
  - psql -c 'create database decent_authentication_test;' -U postgres
  - bundle exec rake db:schema:load

script:
  - RAILS_ENV=test bundle exec rake --trace

notifications:
  email:
    - jeremyleesmith@gmail.com

addons:
  code_climate:
    repo_token: ee12135fbfd5a5486a4f7037951315a2c1a47fd3b854b2a8097b68b6bf129696
